In [1]:
# dataframe的创建方式
import pandas as pd
import numpy as np
# 通过series来创建
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([6,7,8,9,10])
df = pd.DataFrame({'第一列':s1,'第二列':s2})
# 通过字典创建
df = pd.DataFrame({
    'id':[1,2,3,4,5],
    'name':['tom','jack','alice','bob','allen'],
    'age':[15,17,20,26,30],
    'score':[60,70,80,90,10],
},index=[1,2,3,4,5],columns=['id','name','score','age'] #修改顺序
)
df

   id   name  score  age
1   1    tom     60   15
2   2   jack     70   17
3   3  alice     80   20
4   4    bob     90   26
5   5  allen     10   30

In [2]:
# DataFrame的属性
print('行索引')
print(df.index)
print('列索引')
print(df.columns)
print('值')
print(df.values)

行索引
Index([1, 2, 3, 4, 5], dtype='int64')
列索引
Index(['id', 'name', 'score', 'age'], dtype='str')
值
[[1 'tom' 60 15]
 [2 'jack' 70 17]
 [3 'alice' 80 20]
 [4 'bob' 90 26]
 [5 'allen' 10 30]]

In [3]:
print('维度',df.ndim)
print('数据类型',df.dtypes)
print('形状',df.shape)
print('元素个数',df.size)
# 行列转置
print(df.T.index)

维度 2
数据类型 id       int64
name       str
score    int64
age      int64
dtype: object
形状 (5, 4)
元素个数 20
Index(['id', 'name', 'score', 'age'], dtype='str')

In [4]:
# 获取元素 loc iloc at iat
# 某行
print(df.loc[4])
print(df.iloc[3])

id         4
name     bob
score     90
age       26
Name: 4, dtype: object
id         4
name     bob
score     90
age       26
Name: 4, dtype: object

In [5]:
# 某列
print(df.loc[:,'name'])
print(df.iloc[:,0])

1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str
1    1
2    2
3    3
4    4
5    5
Name: id, dtype: int64

In [6]:
# 获取单个元素
print(df.at[3,'score']) # 行 列
print(df.iat[2,1])
print(df.loc[3,'score'])
print(df.iloc[2,1])

80
alice
80
alice

In [7]:
# 获取单列数据
print(df['name'])
print(type(df['name']))
print(df.name)
print(type(df.name))
print(df[['name']])
print(type(df[['name']]))  #dataframe的类型
print(df[['name','score']]) # 获取多列数据

1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str
<class 'pandas.Series'>
1      tom
2     jack
3    alice
4      bob
5    allen
Name: name, dtype: str
<class 'pandas.Series'>
    name
1    tom
2   jack
3  alice
4    bob
5  allen
<class 'pandas.DataFrame'>
    name  score
1    tom     60
2   jack     70
3  alice     80
4    bob     90
5  allen     10

In [8]:
# 查看部分数据
print(df.head(2)) # 获取前两行的数据
print(df.tail(2))

   id  name  score  age
1   1   tom     60   15
2   2  jack     70   17
   id   name  score  age
4   4    bob     90   26
5   5  allen     10   30

In [9]:
# 使用布尔索引来筛选数据
df[df.score>70]
df[(df.score>70)&(df.age<30)]

   id   name  score  age
3   3  alice     80   20
4   4    bob     90   26

In [10]:
# 随机抽样
df.sample()

   id   name  score  age
3   3  alice     80   20

In [11]:
# 通过字典创建
df = pd.DataFrame({
    'id':[1,2,3,4,5,6],
    'name':['tom','jack','alice','bob','allen','h2'],
    'age':[15,17,20,26,30,30],
    'score':[60,70,80,90,10,10],
},index=[1,2,3,4,5,6],columns=['id','name','score','age'] #修改顺序
)
# dataframe的方法
print(df.head()) # 查看前五行
print(df.tail()) # 查看后五行
print(df.isin(['jack',20,80])) # 查看元素是否在df里面
print(df.score.isna()) #查看是否为缺失值
print(df['score'].sum()) #求和
print(df.score.max())  #.是 的 意思
print(df.score.min())
print(df.score.mean()) #平均数
print(df.score.std())
print(df.score.var()) #方差
print(df.score.median()) # 中位数
print(df.score.mode()) # 众数
print(df.score.quantile()) # 分位数
print(df.describe()) # 拿到数据可以用这样来描述
print(df.count()) # 每一列非缺失值的个数

   id   name  score  age
1   1    tom     60   15
2   2   jack     70   17
3   3  alice     80   20
4   4    bob     90   26
5   5  allen     10   30
   id   name  score  age
2   2   jack     70   17
3   3  alice     80   20
4   4    bob     90   26
5   5  allen     10   30
6   6     h2     10   30
      id   name  score    age
1  False  False  False  False
2  False   True  False  False
3  False  False   True   True
4  False  False  False  False
5  False  False  False  False
6  False  False  False  False
1    False
2    False
3    False
4    False
5    False
6    False
Name: score, dtype: bool
320
90
10
53.333333333333336
35.02380143083653
1226.6666666666667
65.0
0    10
Name: score, dtype: int64
65.0
             id      score        age
count  6.000000   6.000000   6.000000
mean   3.500000  53.333333  23.000000
std    1.870829  35.023801   6.572671
min    1.000000  10.000000  15.000000
25%    2.250000  22.500000  17.750000
50%    3.500000  65.000000  23.000000
75%    4.750000  77.500000  29.000000
max    6.000000  90.000000  30.000000
id       6
name     6
score    6
age      6
dtype: int64

In [12]:
print(df.value_counts()) # 重复值出现的次数
print(df.drop_duplicates()) # 去重复值
print(df.duplicated(subset=['score']))  #检查是否重复 subset可以指定检查
df.sample(2) # 随机采2个样
print(df.replace(15,20)) # 将15换成30 替换
df.cumsum() # 累加
df.cummax() #累积的最大
df.cummin(axis=0) # 0按列求 1按行

id  name   score  age
1   tom    60     15     1
2   jack   70     17     1
3   alice  80     20     1
4   bob    90     26     1
5   allen  10     30     1
6   h2     10     30     1
Name: count, dtype: int64
   id   name  score  age
1   1    tom     60   15
2   2   jack     70   17
3   3  alice     80   20
4   4    bob     90   26
5   5  allen     10   30
6   6     h2     10   30
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool
   id   name  score  age
1   1    tom     60   20
2   2   jack     70   17
3   3  alice     80   20
4   4    bob     90   26
5   5  allen     10   30
6   6     h2     10   30

   id   name  score  age
1   1    tom     60   15
2   1   jack     60   15
3   1  alice     60   15
4   1  alice     60   15
5   1  alice     10   15
6   1  alice     10   15

In [13]:
print(df.sort_values(by='score',ascending=False)) # False是从高到低排序
print(df.sort_values(by=['score','age']))# 从低到高排序

   id   name  score  age
4   4    bob     90   26
3   3  alice     80   20
2   2   jack     70   17
1   1    tom     60   15
5   5  allen     10   30
6   6     h2     10   30
   id   name  score  age
5   5  allen     10   30
6   6     h2     10   30
1   1    tom     60   15
2   2   jack     70   17
3   3  alice     80   20
4   4    bob     90   26

In [14]:
df.nlargest(1,columns=['score']) # 取n个最大的数据 从大到小
df.nsmallest(1,columns=['score'])# 取n个最小的数据  从小到大

   id   name  score  age
5   5  allen     10   30