In [9]:
# 数据的导入
import pandas as pd
df = pd.read_excel('datset/附件2.xlsx',engine='openpyxl')
# print(df.head())
# print(df['销量(千克)'].mean())
print(type(df))

<class 'pandas.DataFrame'>

In [10]:
# 数据导出
df = df.tail()
df.to_excel('datset/1.xlsx')

In [ ]:
# json
df = pd.read_json('datset/1.json')
print(type(df))

import json
with open ('datset/1.json') as f:
    data = json.load(f)
print(data)
df = pd.DataFrame(data)
df.to_excel('datset/2.xlsx')

In [39]:
# 缺失值的处理
import pandas as pd
import numpy as np
s = pd.Series([1,2,3,4,np.nan,pd.NA,None])
df = pd.DataFrame({
    '人类':['我','你','他'],
    '成绩':[90,np.nan,70]
})

# 查看是否为缺失值
print(s.isna())
print(s.isnull())
print(df.isnull())
print(df.isna().sum(axis=1)) # 查看缺失值的个数 0按列数
print('-'*10)
# 删除缺失值
print(df.dropna()) # 删除一整条数据
print(df.dropna(how='all')) # 如果所有的值都是缺失值 才删除
print(df.dropna(thresh=1))  # 如果至少有n个值不是缺失值 就保留
print(df.dropna(axis=0))  # 删除一整列的记录
print(df.dropna(subset=['人类'])) #如果某列有缺失值 就删除这一行
print('-'*10)

# 填充缺失值
df = pd.read_excel('datset/附件2.xlsx',engine='openpyxl')
df.isna().sum()
print(df.fillna({'销售日期':20,'销售单价':10})) # 填充某列缺失值
print(df.fillna(df[['销售日期','销售单价(元/千克)']].mean(axis=0)).tail()) # 填充平均值
print(df.ffill()) # 用前面的值填充
print(df.bfill()) # 使用后面的相邻值填充

0    False
1    False
2    False
3    False
4     True
5     True
6     True
dtype: bool
0    False
1    False
2    False
3    False
4     True
5     True
6     True
dtype: bool
      人类     成绩
0  False  False
1  False   True
2  False  False
0    0
1    1
2    0
dtype: int64
----------
  人类    成绩
0  我  90.0
2  他  70.0
  人类    成绩
0  我  90.0
1  你   NaN
2  他  70.0
  人类    成绩
0  我  90.0
1  你   NaN
2  他  70.0
  人类    成绩
0  我  90.0
2  他  70.0
  人类    成绩
0  我  90.0
1  你   NaN
2  他  70.0
----------

销售日期          0
扫码销售时间        0
单品编码          0
销量(千克)        0
销售单价(元/千克)    0
销售类型          0
是否打折销售        0
dtype: int64

In [46]:
# 数据类型转换 去重
data = {
    'name':['alice','alice','bob','alice','jack','bob'],
    'age':[26,25,30,25,35,30],
    'city':['NY','NY','LA','NY','SF','LA'],
}
df = pd.DataFrame(data)
df

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [51]:
df.duplicated() # 一整条记录都是相同的 然后标记为重复，返回为True
df.drop_duplicates(subset=['city'],keep='last') # 根据指定列去重 keep 保留最新出现的结果

    name  age city
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [54]:
# 数据类型的转换
df = pd.read_excel('datset/附件2.xlsx',engine='openpyxl')
df
df.types
df['age'] = df['age'].astype('int16') #转换数据类型
map( ) # 映射的函数

,销售日期,扫码销售时间,单品编码,销量(千克),销售单价(元/千克),销售类型,是否打折销售
0,2020-07-01,09:15:07.924,102900005117056,0.396,7.6,销售,否
1,2020-07-01,09:17:27.295,102900005115960,0.849,3.2,销售,否
2,2020-07-01,09:17:33.905,102900005117056,0.409,7.6,销售,否
3,2020-07-01,09:19:45.450,102900005115823,0.421,10.0,销售,否
4,2020-07-01,09:20:23.686,102900005115908,0.539,8.0,销售,否
...,...,...,...,...,...,...,...
878498,2023-06-30,21:35:13.264,102900005115250,0.284,24.0,销售,否
878499,2023-06-30,21:35:14.358,102900011022764,0.669,12.0,销售,否
878500,2023-06-30,21:35:20.264,102900005115250,0.125,24.0,销售,否
878501,2023-06-30,21:35:21.509,102900011016701,0.252,5.2,销售,否
878502,2023-06-30,21:40:48.248,102900011022764,0.803,12.0,销售,否

In [5]:
# 数据的变形
import pandas as pd
df = pd.DataFrame({
    'ID':[2,3],
    'name':['alice','bob'],
    'Math':[90,85],
    'English':[88,92],
    'Science':[95,89]
})
df.T # 行列转置
print(df)
'''
1 alice math 90
1 alice English 88
1 alice Science 95
'''
# 宽表转变为长表
df2 = pd.melt(df,id_vars=['ID','name'],var_name='科目',value_name='分数')  # 将一个宽表变成一个长表
df2.sort_values('name')
# 长表转为宽表
pd.pivot(df2,index=['ID','name'],columns='科目',values='分数')

   ID   name  Math  English  Science
0   2  alice    90       88       95
1   3    bob    85       92       89

科目        English  Math  Science
ID name
2  alice       88    90       95
3  bob         92    85       89

In [11]:
import pandas as pd
df = pd.DataFrame({
    'ID':[2,3],
    'name':['alice smith','bob smith'],
    'Math':[90,85],
    'English':[88,92],
    'Science':[95,89]
})
# 分列 将一列例如127/14 的这种数据分列
df[['first','last']] =df['name'].str.split(' ',expand=True) # split括号里面填分隔符
df = df['name'].astype('int64') # 要将转为字符串的数据转换回来

   ID         name  Math  English  Science  first   last
0   2  alice smith    90       88       95  alice  smith
1   3    bob smith    85       92       89    bob  smith

In [34]:
# 数据分箱 pd.cut(x,bins,labels)
import pandas as pd
df = pd.read_excel('datset/附件4.xlsx',engine='openpyxl')
df1 = df[['姓名','身高 (cm)']]
print(df1)
pd.cut(df1['身高 (cm)'],bins=2) # bins = n 表示分成了n个区间，起始值，结束值是所有数据的最小值和最大值
# (146.75, 173.5]和(119.946, 146.75]
pd.cut(df1['身高 (cm)'],bins=2).value_counts() # 各个区域里面有多少
pd.cut(df1['身高 (cm)'],bins=[0,160,170]).value_counts() #bins=list,分成n段区间
df1['身高'] = pd.cut(df1['身高 (cm)'],bins=[0,160,170],labels=['低','高']) # 将数据转为选择
pd.qcut(df1['身高 (cm)'],3).value_counts() # 将人数平均分

      姓名  身高 (cm)
0   运动者3    158.1
1   运动者4    172.5
2   运动者5    173.5
3   运动者6    165.8
4   运动者7    168.8
5   运动者8    158.2
6   运动者9    138.7
7  运动者10    166.2
8  运动者11    120.0

身高 (cm)
(119.999, 158.167]    3
(158.167, 167.067]    3
(167.067, 173.5]      3
Name: count, dtype: int64

In [55]:
import pandas as pd
df = pd.read_excel('datset/附件4.xlsx',engine='openpyxl')
df = df[['姓名','性别','身高 (cm)','体重 (kg)']]
df['BMI'] =(df['体重 (kg)']) / (df['身高 (cm)'] /100)**2
df
df['mbi是否正常'] = pd.cut(df['BMI'],bins=[0,18.5,23.9],labels=['瘦','正常'])
df['性别'].astype('category' ) # 将它数据转换成选择
df['性别'] = df['性别'].astype('category' )
df['性别'].value_counts() #查看男女个数
# 字符串--> 类别-->统计
# 数值-->分箱-->统计

性别
男    5
女    4
Name: count, dtype: int64

In [66]:
# df.rename()  df.set_index()  df.reset_index()
df = pd.DataFrame({
    'name':['jack','alice','bob'],
    'age':[20,30,40],
    'gender':['male','female','male'],
})
df.set_index('name',inplace=True) #将某一列设置为索引 不用再设置变量
df.reset_index(inplace=True)
df
df.rename(columns={'age':'年龄'},index={0:4}) # 修改索引与列名
# 全部改用这个
df.index=[1,2,3]
df.columns=['姓名','年龄','性别']